services:
  api:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prova
      POSTGRES_PASSWORD: prova
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  
volumes:
  db_data:

networks:
  app-network:
    driver: bridge