# Usar a imagem oficial do Node
FROM node:20-alpine

# Definir diretório de trabalho dentro do container
WORKDIR /usr/src/

# Copiar package.json e package-lock.json primeiro para aproveitar o cache do Docker
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta da API (mesma do .env, geralmente 3000)
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "main"]
